quicksort algo added
NJACKWinterOfCode/nwoc_algorithms pull request #16
Opened 2019-12-02 14:51 UTC by SaumyaSingh1

2019-12-02 14:52 UTC, SaumyaSingh1 commented
@abhishekchopra13  added quicksort algorithm . Please review if it's the correct format .

2019-12-15 02:07 UTC, Bhavnaharitsa commented on quicksort.cpp
> +the pivot element at its correct position in sorted
push this purpose on top

2019-12-15 02:07 UTC, Bhavnaharitsa commented on quicksort.cpp
> +void swap(int* a, int* b)
add sample input-output

2020-01-06 16:34 UTC, chanmol1999 requested changes
You have to place this inside the algorithms folder.
No Response going to close

2020-01-06 16:34 UTC, closed without merging