Added Graph Algo in c++
NJACKWinterOfCode/nwoc_algorithms pull request #20
Opened 2019-12-02 19:33 UTC by Sahastracookcoder1

- Added algo of articulation point in c++.

2019-12-12 09:46 UTC, chanmol1999 requested changes
Move this inside algorithms folder

2019-12-15 02:21 UTC, Bhavnaharitsa commented on Graph Algorithm/Articulation_Points/C++/articulationpoints.cpp
> +int timee;// a variable to keep track of the time at which a particular vertex is encounterd
spelling check

2019-12-15 02:21 UTC, Bhavnaharitsa commented on Graph Algorithm/Articulation_Points/C++/articulationpoints.cpp
> +void printAP2(int source){
the function name can be printAp2

2019-12-15 02:21 UTC, Bhavnaharitsa commented on Graph Algorithm/Articulation_Points/C++/articulationpoints.cpp
> +		else if(i != parent[source])	low[source] = min(low[i] , low[source]);
avoid unwanted space like i !

2019-12-15 02:21 UTC, Bhavnaharitsa commented on Graph Algorithm/Articulation_Points/C++/articulationpoints.cpp
> +	int n , e , u , v;
avoid single letter variables

2020-01-06 16:37 UTC, chanmol1999 commented
No Response going to close

2020-01-06 16:37 UTC, closed without merging