New Algorithm Added
NJACKWinterOfCode/nwoc_algorithms pull request #45
Opened 2019-12-09 19:13 UTC by vinothgokul

2019-12-14 16:58 UTC, Bhavnaharitsa commented
The title is improper, a new algorithm...what algorithm?
Please add proper titles and description whenever making a pull request and the commit message can be altered..
You can read the commit message guidelines online and the rules while contributing open source.

2019-12-14 17:00 UTC, Bhavnaharitsa commented on Prim's_Algorithm/Prim's_Algorithm.cpp
> +	for (int v = 0; v < V; v++)
no single variables

2019-12-14 17:00 UTC, Bhavnaharitsa commented on README.md
> +[prim's_algorithm.cpp]
please resolve conflicts

2020-01-06 17:00 UTC, chanmol1999 requested changes
Add inside algorithm folder

2020-11-25 15:02 UTC, closed without merging